import { PrismaClient } from '@prisma/client'
import * as bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('Iniciando seed de datos...')

  // Create test user
  const hashedPassword = await bcrypt.hash('password123', 10)
  
  const user = await prisma.user.upsert({
    where: { email: 'demo@jogaboneto.com' },
    update: {},
    create: {
      name: 'Usuario Demo',
      email: 'demo@jogaboneto.com',
      password: hashedPassword,
      userProgress: {
        create: {
          totalPoints: 0,
          currentLevel: 1,
          totalXP: 0,
          currentStreak: 1,
          maxStreak: 1,
          worldsCompleted: 0,
          challengesSolved: 0,
        },
      },
    },
  })

  console.log('Usuario creado:', user.email)

  // Create additional users for leaderboard
  const additionalUsers = await Promise.all([
    prisma.user.upsert({
      where: { email: 'player1@jogaboneto.com' },
      update: {},
      create: {
        name: 'JavaScript Master',
        email: 'player1@jogaboneto.com',
        password: hashedPassword,
        userProgress: {
          create: {
            totalPoints: 2500,
            currentLevel: 25,
            totalXP: 2500,
            currentStreak: 15,
            maxStreak: 20,
            worldsCompleted: 5,
            challengesSolved: 150,
          },
        },
      },
    }),
    prisma.user.upsert({
      where: { email: 'player2@jogaboneto.com' },
      update: {},
      create: {
        name: 'Code Ninja',
        email: 'player2@jogaboneto.com',
        password: hashedPassword,
        userProgress: {
          create: {
            totalPoints: 1800,
            currentLevel: 18,
            totalXP: 1800,
            currentStreak: 10,
            maxStreak: 12,
            worldsCompleted: 3,
            challengesSolved: 100,
          },
        },
      },
    }),
    prisma.user.upsert({
      where: { email: 'player3@jogaboneto.com' },
      update: {},
      create: {
        name: 'Bug Hunter',
        email: 'player3@jogaboneto.com',
        password: hashedPassword,
        userProgress: {
          create: {
            totalPoints: 1200,
            currentLevel: 12,
            totalXP: 1200,
            currentStreak: 7,
            maxStreak: 8,
            worldsCompleted: 2,
            challengesSolved: 70,
          },
        },
      },
    }),
    prisma.user.upsert({
      where: { email: 'player4@jogaboneto.com' },
      update: {},
      create: {
        name: 'Async Wizard',
        email: 'player4@jogaboneto.com',
        password: hashedPassword,
        userProgress: {
          create: {
            totalPoints: 950,
            currentLevel: 9,
            totalXP: 950,
            currentStreak: 5,
            maxStreak: 5,
            worldsCompleted: 2,
            challengesSolved: 55,
          },
        },
      },
    }),
    prisma.user.upsert({
      where: { email: 'player5@jogaboneto.com' },
      update: {},
      create: {
        name: 'Function Guru',
        email: 'player5@jogaboneto.com',
        password: hashedPassword,
        userProgress: {
          create: {
            totalPoints: 750,
            currentLevel: 7,
            totalXP: 750,
            currentStreak: 3,
            maxStreak: 4,
            worldsCompleted: 1,
            challengesSolved: 40,
          },
        },
      },
    }),
  ])

  console.log('Usuarios adicionales creados:', additionalUsers.length)

  // Initialize leaderboard for all users
  const allUsers = await prisma.user.findMany({
    include: {
      userProgress: true,
    },
  })

  // Sort by XP and assign ranks
  const sortedUsers = allUsers
    .filter((u) => u.userProgress.length > 0)
    .sort((a, b) => b.userProgress[0].totalXP - a.userProgress[0].totalXP)

  for (let i = 0; i < sortedUsers.length; i++) {
    const user = sortedUsers[i]
    const progress = user.userProgress[0]

    await prisma.leaderboard.upsert({
      where: { userId: user.id },
      update: {
        rank: i + 1,
        xp: progress.totalXP,
        points: progress.totalPoints,
        level: progress.currentLevel,
        streak: progress.currentStreak,
      },
      create: {
        userId: user.id,
        rank: i + 1,
        xp: progress.totalXP,
        points: progress.totalPoints,
        level: progress.currentLevel,
        streak: progress.currentStreak,
      },
    })
  }

  console.log('Leaderboard inicializado con', sortedUsers.length, 'jugadores')

  // Create badges
  const badges = await prisma.badge.createMany({
    data: [
      {
        name: 'Primeros Pasos',
        description: 'Completa tu primer nivel de JavaScript',
        icon: '🎯',
        color: 'blue',
        type: 'challenges',
        criteria: { challengesSolved: 1 },
      },
      {
        name: 'Maestro de Variables',
        description: 'Completa el Mundo 1: Variables y Constantes',
        icon: '📦',
        color: 'purple',
        type: 'levels',
        criteria: { worldId: 1 },
      },
      {
        name: 'Ninja de Arrays',
        description: 'Completa el Mundo 6: Arrays',
        icon: '🥷',
        color: 'orange',
        type: 'levels',
        criteria: { worldId: 6 },
      },
      {
        name: 'Maestro Asincrono',
        description: 'Completa el Mundo 9: Asincronía',
        icon: '⚡',
        color: 'yellow',
        type: 'levels',
        criteria: { worldId: 9 },
      },
      {
        name: 'Racha de Fuego',
        description: '5 días consecutivos de práctica',
        icon: '🔥',
        color: 'red',
        type: 'streak',
        criteria: { streak: 5 },
      },
      {
        name: 'Explorador',
        description: 'Desbloquea 5 mundos diferentes',
        icon: '🗺️',
        color: 'green',
        type: 'worlds',
        criteria: { worldsUnlocked: 5 },
      },
      {
        name: 'Velocista',
        description: 'Completa un desafío en menos de 30 segundos',
        icon: '💨',
        color: 'cyan',
        type: 'speed',
        criteria: { timeUnderSeconds: 30 },
      },
      {
        name: 'Puntaje Perfecto',
        description: 'Obtén 1000 puntos totales',
        icon: '🏆',
        color: 'gold',
        type: 'points',
        criteria: { totalPoints: 1000 },
      },
    ],
  })

  console.log('Insignias creadas:', badges.length)

  // Create worlds and levels
  const worldsData = [
    {
      order: 1,
      name: 'Variables y Constantes',
      description: 'Aprende a declarar variables y constantes en JavaScript. Los fundamentos de la programación.',
      color: 'blue',
      icon: '🌱',
      requiredLevel: 1,
      requiredXP: 0,
      levels: [
        {
          order: 1,
          name: '¿Qué es una variable?',
          description: 'Aprende a declarar tu primera variable en JavaScript.',
          difficulty: 'beginner',
          concepts: ['let', 'const', 'var', 'declaración'],
          challenges: [
            {
              order: 1,
              title: 'Declara tu primera variable',
              description: 'Declara una variable llamada "nombre" y asígnale el valor "JogaBoneto".',
              instruction: 'Usa la palabra clave "let" para declarar la variable.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n\n',
              expectedSolution: 'let nombre = "JogaBoneto";',
              testCase: { shouldContain: 'let nombre = "JogaBoneto"' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Crear una constante',
              description: 'Crea una constante llamada "MAX_PUNTOS" con el valor 100.',
              instruction: 'Usa "const" para crear una constante que no puede cambiar.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n\n',
              expectedSolution: 'const MAX_PUNTOS = 100;',
              testCase: { shouldContain: 'const MAX_PUNTOS = 100' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Diferencia entre let y const',
              description: '¿Qué palabra clave usarías para un valor que va a cambiar?',
              type: 'quiz',
              instruction: 'Selecciona la respuesta correcta.',
              quizOptions: ['var', 'let', 'const', 'static'],
              correctAnswer: 'let',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
        {
          order: 2,
          name: 'Convenciones de nombres',
          description: 'Aprende buenas prácticas para nombrar tus variables.',
          difficulty: 'beginner',
          concepts: ['camelCase', 'snake_case', 'naming conventions'],
          challenges: [
            {
              order: 1,
              title: 'Nombre apropiado',
              description: 'Declara una variable para guardar el nombre de un usuario.',
              instruction: 'Usa camelCase para nombres compuestos.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n\n',
              expectedSolution: 'let nombreDeUsuario = "Juan";',
              testCase: { shouldContain: 'let nombreDeUsuario' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Constante mayúscula',
              description: 'Declara una constante para la gravedad terrestre.',
              instruction: 'Usa convención de nombres con MAYÚSCULAS para constantes.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n\n',
              expectedSolution: 'const GRAVEDAD_TERRESTRE = 9.8;',
              testCase: { shouldContain: 'const GRAVEDAD_TERRESTRE' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Buenas prácticas',
              description: '¿Cuál es la convención correcta en JavaScript moderno?',
              type: 'quiz',
              instruction: 'Selecciona la opción correcta.',
              quizOptions: [
                'SNAKE_CASE para todo',
                'camelCase para variables, UPPER_CASE para constantes',
                'kebab-case para variables',
                'PascalCase para variables',
              ],
              correctAnswer: 'camelCase para variables, UPPER_CASE para constantes',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
        {
          order: 3,
          name: 'Tipos de datos básicos',
          description: 'Aprende sobre strings, numbers y booleans.',
          difficulty: 'beginner',
          concepts: ['string', 'number', 'boolean', 'typeof'],
          challenges: [
            {
              order: 1,
              title: 'Crear un string',
              description: 'Declara una variable llamada "mensaje" que contenga el texto "Hola Mundo".',
              instruction: 'Usa comillas dobles o simples para crear strings.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n\n',
              expectedSolution: 'let mensaje = "Hola Mundo";',
              testCase: { shouldContain: 'let mensaje = "Hola Mundo"' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Crear un número',
              description: 'Declara una variable llamada "edad" que contenga el número 25.',
              instruction: 'Los números no llevan comillas.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n\n',
              expectedSolution: 'let edad = 25;',
              testCase: { shouldContain: 'let edad = 25' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Booleano verdadero',
              description: 'Crea una variable booleana llamada "esMayorDeEdad" que sea verdadera.',
              instruction: 'Usa las palabras clave true o false.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n\n',
              expectedSolution: 'let esMayorDeEdad = true;',
              testCase: { shouldContain: 'let esMayorDeEdad = true' },
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
      ],
    },
    {
      order: 2,
      name: 'Tipos de Datos Avanzados',
      description: 'Profundiza en null, undefined, Symbol y BigInt.',
      color: 'purple',
      icon: '🔮',
      requiredLevel: 2,
      requiredXP: 100,
      levels: [
        {
          order: 1,
          name: 'Null vs Undefined',
          description: 'Entiende la diferencia entre null y undefined.',
          difficulty: 'intermediate',
          concepts: ['null', 'undefined', 'tipos primitivos'],
          challenges: [
            {
              order: 1,
              title: 'Asignar null',
              description: 'Declara una variable "datos" que tenga el valor null.',
              instruction: 'null se usa cuando una variable intencionalmente no tiene valor.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n\n',
              expectedSolution: 'let datos = null;',
              testCase: { shouldContain: 'let datos = null' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Comprobar undefined',
              description: 'Crea una variable sin asignar valor.',
              instruction: 'Las variables declaradas sin asignar tienen valor undefined.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n\n',
              expectedSolution: 'let variableSinValor;',
              testCase: { shouldContain: 'let variableSinValor' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Tipo de null',
              description: '¿Qué devuelve typeof null?',
              type: 'quiz',
              instruction: 'Selecciona la respuesta correcta.',
              quizOptions: ['undefined', 'null', 'object', 'number'],
              correctAnswer: 'object',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
        {
          order: 2,
          name: 'BigInt y Symbol',
          description: 'Trabaja con números muy grandes y valores únicos.',
          difficulty: 'intermediate',
          concepts: ['BigInt', 'Symbol', 'tipos primitivos'],
          challenges: [
            {
              order: 1,
              title: 'Crear un BigInt',
              description: 'Declara un BigInt para el número 9007199254740991.',
              instruction: 'Usa BigInt() con n al final del número.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n\n',
              expectedSolution: 'let grande = 9007199254740991n;',
              testCase: { shouldContain: 'let grande = 9007199254740991n' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Crear un Symbol',
              description: 'Crea un Symbol con descripción "id-usuario".',
              instruction: 'Los Symbol son siempre únicos.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n\n',
              expectedSolution: 'let idUsuario = Symbol("id-usuario");',
              testCase: { shouldContain: 'let idUsuario = Symbol("id-usuario")' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Característica de Symbol',
              description: '¿Qué propiedad única tienen los Symbols?',
              type: 'quiz',
              instruction: 'Selecciona la respuesta correcta.',
              quizOptions: [
                'Son iterables',
                'Son siempre únicos',
                'Pueden ser convertidos a números',
                'Tienen valor predeterminado',
              ],
              correctAnswer: 'Son siempre únicos',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
        {
          order: 3,
          name: 'Conversión de tipos',
          description: 'Convierte entre diferentes tipos de datos.',
          difficulty: 'intermediate',
          concepts: ['String()', 'Number()', 'Boolean()', 'conversión'],
          challenges: [
            {
              order: 1,
              title: 'String a número',
              description: 'Convierte "42" a número.',
              instruction: 'Usa Number() o el operador +.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\nlet texto = "42";\n',
              expectedSolution: 'let numero = Number(text);',
              testCase: { shouldContain: 'let numero = Number(text)' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Número a string',
              description: 'Convierte 42 a string "42".',
              instruction: 'Usa String().',
              type: 'code',
              initialCode: '// Escribe tu código aquí\nlet numero = 42;\n',
              expectedSolution: 'let texto = String(numero);',
              testCase: { shouldContain: 'let texto = String(numero)' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Booleano a string',
              description: '¿Qué devuelve String(true)?',
              type: 'quiz',
              instruction: 'Selecciona la respuesta correcta.',
              quizOptions: ['true', '"true"', '1', 'undefined'],
              correctAnswer: '"true"',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
      ],
    },
    {
      order: 3,
      name: 'Operadores',
      description: 'Aritméticos, lógicos y de comparación.',
      color: 'green',
      icon: '➕',
      requiredLevel: 3,
      requiredXP: 200,
      levels: [
        {
          order: 1,
          name: 'Operadores Aritméticos',
          description: '+, -, *, /, % y más.',
          difficulty: 'beginner',
          concepts: ['+', '-', '*', '/', '%', 'operadores'],
          challenges: [
            {
              order: 1,
              title: 'Suma',
              description: 'Calcula 5 + 3 y guárdalo en una variable.',
              instruction: 'Usa el operador +.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n',
              expectedSolution: 'let resultado = 5 + 3;',
              testCase: { shouldContain: 'let resultado = 5 + 3' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Módulo',
              description: 'Calcula el módulo de 10 entre 3.',
              instruction: 'El operador % devuelve el residuo.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n',
              expectedSolution: 'let residuo = 10 % 3;',
              testCase: { shouldContain: 'let residuo = 10 % 3' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Exponenciación',
              description: 'Calcula 2 elevado a la 3 (2^3).',
              instruction: 'Usa el operador ** para potenciación.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n',
              expectedSolution: 'let potencia = 2 ** 3;',
              testCase: { shouldContain: 'let potencia = 2 ** 3' },
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
        {
          order: 2,
          name: 'Operadores de Comparación',
          description: '===, !==, <, >, <=, >=.',
          difficulty: 'beginner',
          concepts: ['===', '!==', '<', '>', '<=', '>='],
          challenges: [
            {
              order: 1,
              title: 'Igualdad estricta',
              description: 'Compara si 5 es igual a "5".',
              instruction: '=== compara valor y tipo.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n',
              expectedSolution: 'let esIgual = 5 === "5";',
              testCase: { shouldContain: 'let esIgual = 5 === "5"' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Mayor que',
              description: 'Compara si 10 es mayor que 5.',
              instruction: 'Usa el operador >.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n',
              expectedSolution: 'let esMayor = 10 > 5;',
              testCase: { shouldContain: 'let esMayor = 10 > 5' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Diferente de',
              description: '¿Qué operador devuelve true si los valores son diferentes?',
              type: 'quiz',
              instruction: 'Selecciona la respuesta correcta.',
              quizOptions: ['==', '===', '!==', '='],
              correctAnswer: '!==',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
        {
          order: 3,
          name: 'Operadores Lógicos',
          description: '&&, ||, ! y más.',
          difficulty: 'intermediate',
          concepts: ['&&', '||', '!', 'operadores lógicos'],
          challenges: [
            {
              order: 1,
              title: 'AND lógico',
              description: 'Verifica si esAdulto Y tieneLicencia.',
              instruction: 'Ambas condiciones deben ser verdaderas.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\nlet esAdulto = true;\nlet tieneLicencia = true;\n',
              expectedSolution: 'let puedeConducir = esAdulto && tieneLicencia;',
              testCase: { shouldContain: 'let puedeConducir = esAdulto && tieneLicencia' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 2,
              title: 'OR lógico',
              description: 'Verifica si esFinDeSemana O esVacación.',
              instruction: 'Al menos una condición debe ser verdadera.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\nlet esFinDeSemana = false;\nlet esVacación = true;\n',
              expectedSolution: 'let puedeDescansar = esFinDeSemana || esVacación;',
              testCase: { shouldContain: 'let puedeDescansar = esFinDeSemana || esVacación' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 3,
              title: 'NOT lógico',
              description: 'Invierte el valor de una boolean.',
              instruction: 'Usa el operador !.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\nlet esVerdadero = true;\n',
              expectedSolution: 'let esFalso = !esVerdadero;',
              testCase: { shouldContain: 'let esFalso = !esVerdadero' },
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
      ],
    },
    // Worlds 4-9 would follow the same pattern...
    {
      order: 4,
      name: 'Control de Flujo',
      description: 'Condicionales if/else y bucles for/while.',
      color: 'orange',
      icon: '🔀',
      requiredLevel: 4,
      requiredXP: 300,
      levels: [
        {
          order: 1,
          name: 'Condicionales Básicas',
          description: 'Aprende a usar if/else para tomar decisiones en tu código.',
          difficulty: 'beginner',
          concepts: ['if', 'else', 'condicionales', 'toma de decisiones'],
          challenges: [
            {
              order: 1,
              title: 'Par o Impar',
              description: 'Crea una función que retorne "par" si el número es par, o "impar" si es impar.',
              instruction: 'Usa if/else y el operador módulo (%) para determinar si un número es par o impar.',
              type: 'code',
              initialCode: 'function parOImpar(numero) {\n  // Tu código aquí\n  \n}',
              expectedSolution: 'function parOImpar(numero) {\n  if (numero % 2 === 0) {\n    return "par";\n  } else {\n    return "impar";\n  }\n}',
              testCase: { shouldContain: 'if (numero % 2 === 0)', shouldContain: 'return "par"' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Validación de Usuario',
              description: 'Verifica si un usuario puede entrar: debe ser mayor de 18 años Y tener entrada.',
              instruction: 'Usa el operador lógico && (AND) para combinar condiciones.',
              type: 'code',
              initialCode: 'function puedeEntrar(edad, tieneEntrada) {\n  // Tu código aquí\n  \n}',
              expectedSolution: 'function puedeEntrar(edad, tieneEntrada) {\n  if (edad >= 18 && tieneEntrada) {\n    return true;\n  } else {\n    return false;\n  }\n}',
              testCase: { shouldContain: 'edad >= 18 && tieneEntrada' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 3,
              title: '=== vs ==',
              description: '¿Qué operador compara tanto el valor como el tipo de dato?',
              instruction: 'Selecciona la respuesta correcta.',
              type: 'quiz',
              quizOptions: ['==', '===', '=', '!=='],
              correctAnswer: '===',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
        {
          order: 2,
          name: 'Condicionales Avanzadas',
          description: 'Domina switch, operador ternario y else if.',
          difficulty: 'intermediate',
          concepts: ['switch', 'ternario', 'else if', 'condicionales encadenadas'],
          challenges: [
            {
              order: 1,
              title: 'Día de la Semana',
              description: 'Convierte un número (1-7) al nombre del día correspondiente.',
              instruction: 'Usa switch para retornar el nombre del día. 1 = "Lunes", 2 = "Martes", etc.',
              type: 'code',
              initialCode: 'function diaDeLaSemana(numero) {\n  // Tu código aquí\n  switch (numero) {\n    \n  }\n}',
              expectedSolution: 'function diaDeLaSemana(numero) {\n  switch (numero) {\n    case 1: return "Lunes";\n    case 2: return "Martes";\n    case 3: return "Miércoles";\n    case 4: return "Jueves";\n    case 5: return "Viernes";\n    case 6: return "Sábado";\n    case 7: return "Domingo";\n    default: return "Día inválido";\n  }\n}',
              testCase: { shouldContain: 'case 1:', shouldContain: 'return "Lunes"' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Operador Ternario',
              description: 'Usa el operador ternario para verificar si puede votar (edad >= 18).',
              instruction: 'El operador ternario tiene la forma: condición ? valorSiVerdadero : valorSiFalso',
              type: 'code',
              initialCode: 'function puedeVotar(edad) {\n  // Usa el operador ternario\n  return \n}',
              expectedSolution: 'function puedeVotar(edad) {\n  return edad >= 18 ? "Puede votar" : "No puede votar";\n}',
              testCase: { shouldContain: 'edad >= 18 ?' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Clasificación de Notas',
              description: 'Clasifica una nota: A(90-100), B(80-89), C(70-79), D(60-69), F(<60).',
              instruction: 'Usa if/else if/else para retornar la letra correspondiente.',
              type: 'code',
              initialCode: 'function clasificarNota(nota) {\n  // Tu código aquí\n  \n}',
              expectedSolution: 'function clasificarNota(nota) {\n  if (nota >= 90) return "A";\n  else if (nota >= 80) return "B";\n  else if (nota >= 70) return "C";\n  else if (nota >= 60) return "D";\n  else return "F";\n}',
              testCase: { shouldContain: 'else if' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
          ],
        },
        {
          order: 3,
          name: 'Lógica Compleja',
          description: 'Aplica condicionales anidadas y lógica de negocio real.',
          difficulty: 'intermediate',
          concepts: ['anidación', 'lógica de negocio', 'validación múltiple'],
          challenges: [
            {
              order: 1,
              title: 'Validador de Formulario',
              description: 'Valida un registro: email válido (@ incluido), password >= 6 caracteres, y passwords coincidan.',
              instruction: 'Usa condicionales anidadas para validar todos los campos.',
              type: 'code',
              initialCode: 'function validarRegistro(email, password, confirmarPassword) {\n  // Retorna true si todo es válido, false si hay error\n  \n}',
              expectedSolution: 'function validarRegistro(email, password, confirmarPassword) {\n  if (email.includes("@")) {\n    if (password.length >= 6) {\n      if (password === confirmarPassword) {\n        return true;\n      } else {\n        return false;\n      }\n    } else {\n      return false;\n    }\n  } else {\n    return false;\n  }\n}',
              testCase: { shouldContain: 'email.includes("@")', shouldContain: 'password.length >= 6' },
              points: 20,
              xp: 15,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Sistema de Descuentos',
              description: 'Calcula descuento: estudiante 10%, +$100 compra 15% extra, VIP 20% extra (máximo 45%).',
              instruction: 'Los descuentos son acumulativos pero el máximo es 45%.',
              type: 'code',
              initialCode: 'function calcularDescuento(total, esEstudiante, esVIP) {\n  let descuento = 0;\n  // Tu código aquí\n  \n}',
              expectedSolution: 'function calcularDescuento(total, esEstudiante, esVIP) {\n  let descuento = 0;\n  if (esEstudiante) descuento += 10;\n  if (total >= 100) descuento += 15;\n  if (esVIP) descuento += 20;\n  if (descuento > 45) descuento = 45;\n  return descuento;\n}',
              testCase: { shouldContain: 'if (esEstudiante)', shouldContain: 'if (descuento > 45)' },
              points: 20,
              xp: 15,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Calculadora de Envíos',
              description: 'Calcula el costo de envío: gratis para compras >$50, $5 normal, $10 express.',
              instruction: 'Usa if/else if/else con múltiples condiciones.',
              type: 'quiz',
              quizOptions: [
                'if (total > 50) return 0; else if (express) return 10; else return 5;',
                'if (express) return 10; if (total > 50) return 0; return 5;',
                'return total > 50 ? 0 : (express ? 10 : 5);',
                'Todas las anteriores son válidas',
              ],
              correctAnswer: 'Todas las anteriores son válidas',
              points: 15,
              xp: 10,
              isRequired: false,
            },
          ],
        },
      ],
    },
    {
      order: 5,
      name: 'Funciones',
      description: 'Declaración, expresión, flecha y más.',
      color: 'red',
      icon: '📦',
      requiredLevel: 5,
      requiredXP: 400,
      levels: [
        {
          order: 1,
          name: 'Fundamentos de Funciones',
          description: 'Aprende a declarar funciones y usar parámetros.',
          difficulty: 'beginner',
          concepts: ['function', 'parámetros', 'return', 'declaración'],
          challenges: [
            {
              order: 1,
              title: 'Función de Saludo',
              description: 'Crea una función llamada "saludar" que retorne "Hola, [nombre]".',
              instruction: 'Usa la palabra clave "function" para declarar tu función.',
              type: 'code',
              initialCode: '// Tu código aquí\n\n',
              expectedSolution: 'function saludar(nombre) {\n  return "Hola, " + nombre;\n}',
              testCase: { shouldContain: 'function saludar', shouldContain: 'return' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Función de Suma',
              description: 'Crea una función "sumar" que reciba dos parámetros y retorne su suma.',
              instruction: 'Los parámetros se definen entre paréntesis después del nombre.',
              type: 'code',
              initialCode: '// Tu código aquí\n\n',
              expectedSolution: 'function sumar(a, b) {\n  return a + b;\n}',
              testCase: { shouldContain: 'function sumar(a, b)' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Valor de Retorno',
              description: '¿Qué palabra clave se usa para devolver un valor desde una función?',
              instruction: 'Selecciona la respuesta correcta.',
              type: 'quiz',
              quizOptions: ['return', 'output', 'yield', 'export'],
              correctAnswer: 'return',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
        {
          order: 2,
          name: 'Scope y Closures',
          description: 'Entiende el alcance de variables y los closures.',
          difficulty: 'intermediate',
          concepts: ['scope', 'closure', 'variable global', 'variable local'],
          challenges: [
            {
              order: 1,
              title: 'Variable Global vs Local',
              description: 'Completa la función para usar la variable local si existe, sino la global.',
              instruction: 'Las variables declaradas dentro de una función son locales.',
              type: 'code',
              initialCode: 'let mensaje = "Global";\n\nfunction mostrarMensaje() {\n  let mensaje = "Local";\n  // Retorna la variable local\n  return \n}',
              expectedSolution: 'let mensaje = "Global";\n\nfunction mostrarMensaje() {\n  let mensaje = "Local";\n  return mensaje;\n}',
              testCase: { shouldContain: 'return mensaje;' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Contador con Closure',
              description: 'Crea una función que retorna otra función que incrementa un contador.',
              instruction: 'Un closure permite a una función acceder a variables de su función padre.',
              type: 'code',
              initialCode: 'function crearContador() {\n  let contador = 0;\n  // Retorna una función que incrementa y retorna contador\n  return function() {\n    \n  };\n}',
              expectedSolution: 'function crearContador() {\n  let contador = 0;\n  return function() {\n    contador++;\n    return contador;\n  };\n}',
              testCase: { shouldContain: 'contador++', shouldContain: 'return contador' },
              points: 20,
              xp: 15,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Callback',
              description: '¿Qué es un callback?',
              instruction: 'Selecciona la respuesta correcta.',
              type: 'quiz',
              quizOptions: [
                'Una función que se ejecuta al inicio del código',
                'Una función pasada como argumento a otra función',
                'Un tipo de variable especial',
                'Un método de arrays',
              ],
              correctAnswer: 'Una función pasada como argumento a otra función',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
        {
          order: 3,
          name: 'Arrow Functions',
          description: 'Domina la sintaxis moderna de flecha.',
          difficulty: 'intermediate',
          concepts: ['arrow function', '=>', 'return implícito', 'función flecha'],
          challenges: [
            {
              order: 1,
              title: 'Convertir a Arrow Function',
              description: 'Convierte esta función tradicional a arrow function: function duplicar(n) { return n * 2; }',
              instruction: 'Usa la sintaxis: const nombre = (params) => { cuerpo }',
              type: 'code',
              initialCode: '// Tu código aquí\n\n',
              expectedSolution: 'const duplicar = (n) => { return n * 2; };',
              testCase: { shouldContain: 'const duplicar = (n) =>' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Arrow con Un Parámetro',
              description: 'Simplifica esta arrow function: (nombre) => { return "Hola " + nombre; }',
              instruction: 'Con un solo parámetro puedes omitir los paréntesis.',
              type: 'code',
              initialCode: '// Simplifica esta función\nconst saludar = (nombre) => { return "Hola " + nombre; };\n\n// Versión simplificada:\n',
              expectedSolution: 'const saludar = nombre => "Hola " + nombre;',
              testCase: { shouldContain: 'nombre =>' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Return Implícito',
              description: '¿Cuándo puedes omitir las llaves y return en una arrow function?',
              instruction: 'Selecciona la respuesta correcta.',
              type: 'quiz',
              quizOptions: [
                'Siempre',
                'Nunca',
                'Cuando el cuerpo es una sola expresión',
                'Solo cuando no tiene parámetros',
              ],
              correctAnswer: 'Cuando el cuerpo es una sola expresión',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
      ],
    },
    {
      order: 6,
      name: 'Arrays',
      description: 'Creación, métodos y manipulación de arrays.',
      color: 'pink',
      icon: '🥷',
      requiredLevel: 6,
      requiredXP: 500,
      levels: [
        {
          order: 1,
          name: 'Métodos Básicos',
          description: 'Aprende a agregar, quitar y acceder a elementos.',
          difficulty: 'beginner',
          concepts: ['push', 'pop', 'shift', 'unshift', 'índices'],
          challenges: [
            {
              order: 1,
              title: 'Agregar y Quitar Elementos',
              description: 'Agrega "mango" al final del array y luego quita el último elemento.',
              instruction: 'Usa push() para agregar y pop() para quitar el último elemento.',
              type: 'code',
              initialCode: 'let frutas = ["manzana", "banana", "naranja"];\n\n// Agrega "mango" al final\n\n// Quita el último elemento\n',
              expectedSolution: 'let frutas = ["manzana", "banana", "naranja"];\nfrutas.push("mango");\nfrutas.pop();',
              testCase: { shouldContain: 'frutas.push("mango")', shouldContain: 'frutas.pop()' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Modificar el Inicio',
              description: 'Agrega "primero" al inicio y luego quita el primer elemento.',
              instruction: 'Usa unshift() para agregar al inicio y shift() para quitar del inicio.',
              type: 'code',
              initialCode: 'let numeros = [2, 3, 4, 5];\n\n// Agrega 1 al inicio\n\n// Quita el primer elemento\n',
              expectedSolution: 'let numeros = [2, 3, 4, 5];\nnumeros.unshift(1);\nnumeros.shift();',
              testCase: { shouldContain: 'numeros.unshift(1)', shouldContain: 'numeros.shift()' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Acceder por Índice',
              description: '¿Cómo obtienes el tercer elemento de un array?',
              instruction: 'Recuerda que los índices empiezan en 0.',
              type: 'quiz',
              quizOptions: [
                'array[3]',
                'array(2)',
                'array[2]',
                'array.third',
              ],
              correctAnswer: 'array[2]',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
        {
          order: 2,
          name: 'Métodos Avanzados',
          description: 'Domina map, filter y reduce.',
          difficulty: 'intermediate',
          concepts: ['map', 'filter', 'reduce', 'inmutabilidad'],
          challenges: [
            {
              order: 1,
              title: 'Transformar con Map',
              description: 'Usa map() para crear un nuevo array con todos los números duplicados.',
              instruction: 'map() crea un nuevo array transformando cada elemento.',
              type: 'code',
              initialCode: 'let numeros = [1, 2, 3, 4, 5];\n\n// Usa map para duplicar cada número\nlet duplicados = numeros.map( => \n);',
              expectedSolution: 'let numeros = [1, 2, 3, 4, 5];\nlet duplicados = numeros.map(num => num * 2);',
              testCase: { shouldContain: 'numeros.map(', shouldContain: 'num * 2' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Filtrar Array',
              description: 'Usa filter() para obtener solo los números pares del array.',
              instruction: 'filter() crea un nuevo array solo con elementos que cumplen la condición.',
              type: 'code',
              initialCode: 'let numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];\n\n// Usa filter para obtener solo pares\nlet pares = numeros.filter( => \n);',
              expectedSolution: 'let numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];\nlet pares = numeros.filter(num => num % 2 === 0);',
              testCase: { shouldContain: 'numeros.filter(', shouldContain: 'num % 2 === 0' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Sumar con Reduce',
              description: 'Usa reduce() para sumar todos los elementos del array.',
              instruction: 'reduce() acumula todos los elementos en un solo valor.',
              type: 'code',
              initialCode: 'let numeros = [1, 2, 3, 4, 5];\n\n// Usa reduce para sumar todos los números\nlet suma = numeros.reduce(, 0);',
              expectedSolution: 'let numeros = [1, 2, 3, 4, 5];\nlet suma = numeros.reduce((acc, num) => acc + num, 0);',
              testCase: { shouldContain: 'reduce((acc, num) => acc + num' },
              points: 20,
              xp: 15,
              isRequired: true,
            },
          ],
        },
        {
          order: 3,
          name: 'Iteración y Búsqueda',
          description: 'Recorre arrays y busca elementos específicos.',
          difficulty: 'intermediate',
          concepts: ['forEach', 'find', 'includes', 'indexOf', 'búsqueda'],
          challenges: [
            {
              order: 1,
              title: 'Iterar con forEach',
              description: 'Usa forEach() para mostrar cada nombre del array en consola.',
              instruction: 'forEach() ejecuta una función por cada elemento del array.',
              type: 'code',
              initialCode: 'let nombres = ["Ana", "Beto", "Carlos", "Diana"];\n\n// Usa forEach para mostrar cada nombre\n',
              expectedSolution: 'let nombres = ["Ana", "Beto", "Carlos", "Diana"];\nnombres.forEach(nombre => console.log(nombre));',
              testCase: { shouldContain: 'forEach(' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Buscar Elemento',
              description: 'Usa find() para encontrar el primer número mayor que 5.',
              instruction: 'find() retorna el primer elemento que cumple la condición.',
              type: 'code',
              initialCode: 'let numeros = [1, 3, 5, 7, 9, 11];\n\n// Usa find para buscar el primer número mayor que 5\nlet encontrado = numeros.find( => \n);',
              expectedSolution: 'let numeros = [1, 3, 5, 7, 9, 11];\nlet encontrado = numeros.find(num => num > 5);',
              testCase: { shouldContain: 'numeros.find(', shouldContain: 'num > 5' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Verificar Existencia',
              description: '¿Qué método retorna true si un elemento existe en el array?',
              instruction: 'Selecciona la respuesta correcta.',
              type: 'quiz',
              quizOptions: [
                'exists()',
                'contains()',
                'includes()',
                'has()',
              ],
              correctAnswer: 'includes()',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
      ],
    },
    {
      order: 7,
      name: 'Objetos',
      description: 'Propiedades, métodos y clases básicas.',
      color: 'indigo',
      icon: '💎',
      requiredLevel: 7,
      requiredXP: 600,
      levels: [
        {
          order: 1,
          name: 'Fundamentos de Objetos',
          description: 'Aprende a crear y manipular objetos literales en JavaScript.',
          difficulty: 'intermediate',
          concepts: ['objetos', 'propiedades', 'dot notation', 'bracket notation'],
          challenges: [
            {
              order: 1,
              title: 'Crear un objeto persona',
              description: 'Crea un objeto literal llamado "persona" con las propiedades: nombre (string), edad (number) y esEstudiante (boolean).',
              instruction: 'Usa la sintaxis de objeto literal con llaves {} y separa las propiedades con comas.',
              type: 'code',
              initialCode: '// Crea el objeto persona aquí\n\n',
              expectedSolution: 'let persona = { nombre: "Juan", edad: 25, esEstudiante: true };',
              testCase: { shouldContain: 'let persona', shouldContain: 'nombre', shouldContain: 'edad', shouldContain: 'esEstudiante' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Acceso a propiedades',
              description: 'Accede a la propiedad "nombre" del objeto usuario usando dot notation.',
              instruction: 'Usa el punto (.) para acceder a la propiedad.',
              type: 'code',
              initialCode: 'let usuario = { nombre: "María", edad: 30 };\n// Accede a la propiedad nombre\nlet nombreUsuario = \n',
              expectedSolution: 'let nombreUsuario = usuario.nombre;',
              testCase: { shouldContain: 'usuario.nombre' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Bracket notation',
              description: '¿Cuándo es necesario usar bracket notation para acceder a una propiedad?',
              type: 'quiz',
              instruction: 'Selecciona la respuesta correcta.',
              quizOptions: [
                'Siempre es mejor que dot notation',
                'Cuando el nombre de la propiedad tiene espacios o caracteres especiales',
                'Solo para propiedades de tipo número',
                'Nunca se debe usar',
              ],
              correctAnswer: 'Cuando el nombre de la propiedad tiene espacios o caracteres especiales',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
        {
          order: 2,
          name: 'Métodos y This',
          description: 'Agrega funcionalidad a tus objetos con métodos y entiende el contexto de this.',
          difficulty: 'intermediate',
          concepts: ['métodos', 'this', 'Object.keys', 'Object.values'],
          challenges: [
            {
              order: 1,
              title: 'Agregar método a objeto',
              description: 'Agrega un método llamado "saludar" al objeto persona que retorne "Hola, soy [nombre]".',
              instruction: 'Los métodos son funciones que son propiedades de un objeto.',
              type: 'code',
              initialCode: 'let persona = {\n  nombre: "Ana",\n  // Agrega el método saludar aquí\n  \n};',
              expectedSolution: 'let persona = {\n  nombre: "Ana",\n  saludar: function() { return "Hola, soy " + this.nombre; }\n};',
              testCase: { shouldContain: 'saludar', shouldContain: 'function' },
              points: 20,
              xp: 10,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Usar this en método',
              description: 'Completa el método "presentarse" para que use this y retorne el nombre y la edad.',
              instruction: 'Usa this.nombre y this.edad para acceder a las propiedades del objeto.',
              type: 'code',
              initialCode: 'let persona = {\n  nombre: "Carlos",\n  edad: 28,\n  presentarse: function() {\n    return "Soy " + ___ + " y tengo " + ___ + " años";\n  }\n};',
              expectedSolution: 'let persona = {\n  nombre: "Carlos",\n  edad: 28,\n  presentarse: function() {\n    return "Soy " + this.nombre + " y tengo " + this.edad + " años";\n  }\n};',
              testCase: { shouldContain: 'this.nombre', shouldContain: 'this.edad' },
              points: 20,
              xp: 10,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Object.keys() y Object.values()',
              description: '¿Qué devuelve Object.keys({ a: 1, b: 2, c: 3 })?',
              type: 'quiz',
              instruction: 'Selecciona la respuesta correcta.',
              quizOptions: [
                '[1, 2, 3]',
                '["a", "b", "c"]',
                '{ a: 1, b: 2, c: 3 }',
                'undefined',
              ],
              correctAnswer: '["a", "b", "c"]',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
        {
          order: 3,
          name: 'Operadores Avanzados',
          description: 'Destructuring, spread operator e inmutabilidad con objetos.',
          difficulty: 'intermediate',
          concepts: ['destructuring', 'spread operator', 'inmutabilidad', 'Object.assign'],
          challenges: [
            {
              order: 1,
              title: 'Destructuring de objetos',
              description: 'Usa destructuring para extraer las propiedades "nombre" y "edad" del objeto usuario.',
              instruction: 'Usa la sintaxis: const { nombre, edad } = objeto;',
              type: 'code',
              initialCode: 'let usuario = { nombre: "Laura", edad: 32, ciudad: "Madrid" };\n// Usa destructuring aquí\n',
              expectedSolution: 'let usuario = { nombre: "Laura", edad: 32, ciudad: "Madrid" };\nconst { nombre, edad } = usuario;',
              testCase: { shouldContain: 'const { nombre, edad }' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Spread operator en objetos',
              description: 'Crea un nuevo objeto "usuarioCompleto" que copie todas las propiedades de "usuario" y agregue "email".',
              instruction: 'Usa el spread operator ... para copiar las propiedades.',
              type: 'code',
              initialCode: 'let usuario = { nombre: "Pedro", edad: 25 };\n// Crea usuarioCompleto usando spread operator\nlet usuarioCompleto = { \n  ...usuario,\n  email: "pedro@email.com"\n};',
              expectedSolution: 'let usuario = { nombre: "Pedro", edad: 25 };\nlet usuarioCompleto = { \n  ...usuario,\n  email: "pedro@email.com"\n};',
              testCase: { shouldContain: '...usuario' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Inmutabilidad',
              description: '¿Cuál es la mejor forma de crear una copia de un objeto sin modificar el original?',
              type: 'quiz',
              instruction: 'Selecciona la respuesta correcta.',
              quizOptions: [
                'Asignar el objeto a una nueva variable',
                'Usar spread operator o Object.assign()',
                'Modificar el objeto directamente',
                'Usar delete en el objeto original',
              ],
              correctAnswer: 'Usar spread operator o Object.assign()',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
      ],
    },
    {
      order: 8,
      name: 'DOM Manipulation',
      description: 'Seleccionar, modificar y crear elementos HTML.',
      color: 'teal',
      icon: '🌐',
      requiredLevel: 8,
      requiredXP: 700,
      levels: [
        {
          order: 1,
          name: 'Selección de Elementos',
          description: 'Aprende a seleccionar elementos del DOM usando diferentes métodos.',
          difficulty: 'intermediate',
          concepts: ['querySelector', 'getElementById', 'querySelectorAll', 'selectores CSS'],
          challenges: [
            {
              order: 1,
              title: 'Seleccionar por clase',
              description: 'Selecciona el elemento con la clase "titulo-principal" usando querySelector.',
              instruction: 'Usa document.querySelector() con el selector de clase (.)',
              type: 'code',
              initialCode: '// Selecciona el elemento con clase "titulo-principal"\nlet titulo = \n',
              expectedSolution: "let titulo = document.querySelector('.titulo-principal');",
              testCase: { shouldContain: 'document.querySelector', shouldContain: '.titulo-principal' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Seleccionar por ID',
              description: 'Selecciona el elemento con el id "mi-boton" usando getElementById.',
              instruction: 'Usa document.getElementById() que es más rápido para IDs.',
              type: 'code',
              initialCode: '// Selecciona el elemento con id "mi-boton"\nlet boton = \n',
              expectedSolution: 'let boton = document.getElementById("mi-boton");',
              testCase: { shouldContain: 'document.getElementById', shouldContain: 'mi-boton' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Seleccionar múltiples elementos',
              description: '¿Qué método usarías para seleccionar TODOS los elementos con la clase "item"?',
              type: 'quiz',
              instruction: 'Selecciona la respuesta correcta.',
              quizOptions: [
                'document.querySelector(".item")',
                'document.getElementById("item")',
                'document.querySelectorAll(".item")',
                'document.getElementByClass("item")',
              ],
              correctAnswer: 'document.querySelectorAll(".item")',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
        {
          order: 2,
          name: 'Eventos del DOM',
          description: 'Aprende a escuchar y responder a eventos del usuario.',
          difficulty: 'intermediate',
          concepts: ['addEventListener', 'click', 'input', 'submit', 'event object'],
          challenges: [
            {
              order: 1,
              title: 'Agregar event listener click',
              description: 'Agrega un event listener de tipo "click" al botón que muestre una alerta.',
              instruction: 'Usa el método addEventListener() con "click" como primer parámetro.',
              type: 'code',
              initialCode: 'let boton = document.querySelector("#mi-boton");\n// Agrega el event listener click aquí\n\n',
              expectedSolution: "boton.addEventListener('click', function() {\n  alert('¡Click!');\n});",
              testCase: { shouldContain: 'addEventListener', shouldContain: 'click' },
              points: 20,
              xp: 10,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Capturar valor de input',
              description: 'Captura el valor del input cuando el usuario escribe y guárdalo en una variable.',
              instruction: 'Usa el evento "input" y accede a event.target.value.',
              type: 'code',
              initialCode: 'let input = document.querySelector("#mi-input");\ninput.addEventListener("input", function(event) {\n  let valor = ___; // Completa aquí\n  console.log(valor);\n});',
              expectedSolution: 'let input = document.querySelector("#mi-input");\ninput.addEventListener("input", function(event) {\n  let valor = event.target.value;\n  console.log(valor);\n});',
              testCase: { shouldContain: 'event.target.value' },
              points: 20,
              xp: 10,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Prevenir submit de formulario',
              description: '¿Qué método del objeto event se usa para prevenir el comportamiento por defecto de un formulario?',
              type: 'quiz',
              instruction: 'Selecciona la respuesta correcta.',
              quizOptions: [
                'event.stop()',
                'event.preventDefault()',
                'event.cancel()',
                'event.block()',
              ],
              correctAnswer: 'event.preventDefault()',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
        {
          order: 3,
          name: 'Manipulación de Elementos',
          description: 'Modifica el contenido, estilo y estructura del DOM.',
          difficulty: 'intermediate',
          concepts: ['textContent', 'innerHTML', 'classList', 'createElement', 'appendChild'],
          challenges: [
            {
              order: 1,
              title: 'Cambiar texto de elemento',
              description: 'Cambia el texto del elemento con id "mensaje" a "¡Hola Mundo!"',
              instruction: 'Usa la propiedad textContent para modificar el texto.',
              type: 'code',
              initialCode: 'let elemento = document.getElementById("mensaje");\n// Cambia el texto aquí\n',
              expectedSolution: 'let elemento = document.getElementById("mensaje");\nelemento.textContent = "¡Hola Mundo!";',
              testCase: { shouldContain: 'textContent', shouldContain: '¡Hola Mundo!' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Agregar y remover clases',
              description: 'Agrega la clase "activo" al elemento usando classList.',
              instruction: 'Usa el método add() de classList.',
              type: 'code',
              initialCode: 'let elemento = document.querySelector(".mi-elemento");\n// Agrega la clase "activo"\n',
              expectedSolution: 'let elemento = document.querySelector(".mi-elemento");\nelemento.classList.add("activo");',
              testCase: { shouldContain: 'classList.add' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Crear elemento dinámicamente',
              description: '¿Qué método se usa para crear un nuevo elemento HTML en JavaScript?',
              type: 'quiz',
              instruction: 'Selecciona la respuesta correcta.',
              quizOptions: [
                'document.makeElement()',
                'document.newElement()',
                'document.createElement()',
                'document.createHTML()',
              ],
              correctAnswer: 'document.createElement()',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
      ],
    },
    {
      order: 9,
      name: 'Asincronía',
      description: 'Promesas, async/await y fetch API.',
      color: 'yellow',
      icon: '⚡',
      requiredLevel: 9,
      requiredXP: 800,
      levels: [
        {
          order: 1,
          name: 'Timers y Funciones Asíncronas',
          description: 'Aprende a trabajar con setTimeout, setInterval y clearTimeout.',
          difficulty: 'intermediate',
          concepts: ['setTimeout', 'setInterval', 'clearInterval', 'clearTimeout'],
          challenges: [
            {
              order: 1,
              title: 'Usar setTimeout',
              description: 'Usa setTimeout para ejecutar una función que muestre "¡Hola después de 2 segundos!" después de 2000ms.',
              instruction: 'setTimeout recibe una función y el tiempo en milisegundos.',
              type: 'code',
              initialCode: '// Usa setTimeout para mostrar el mensaje después de 2 segundos\n\n',
              expectedSolution: "setTimeout(function() {\n  console.log('¡Hola después de 2 segundos!');\n}, 2000);",
              testCase: { shouldContain: 'setTimeout', shouldContain: '2000' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Usar setInterval',
              description: 'Crea un intervalo que ejecute una función cada segundo (1000ms).',
              instruction: 'setInterval ejecuta la función repetidamente cada cierto tiempo.',
              type: 'code',
              initialCode: '// Crea un intervalo que se ejecute cada segundo\nlet intervalo = \n',
              expectedSolution: "setInterval(function() {\n  console.log('Tic tac...');\n}, 1000);",
              testCase: { shouldContain: 'setInterval', shouldContain: '1000' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Detener un intervalo',
              description: '¿Qué método se usa para detener un setInterval que está ejecutándose?',
              type: 'quiz',
              instruction: 'Selecciona la respuesta correcta.',
              quizOptions: [
                'stopInterval()',
                'clearInterval()',
                'removeInterval()',
                'cancelInterval()',
              ],
              correctAnswer: 'clearInterval()',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
        {
          order: 2,
          name: 'Promesas',
          description: 'Entiende el funcionamiento de las Promesas en JavaScript.',
          difficulty: 'intermediate',
          concepts: ['Promise', 'resolve', 'reject', 'then', 'catch', 'Promise.all'],
          challenges: [
            {
              order: 1,
              title: 'Crear una promesa',
              description: 'Crea una nueva Promise que se resuelva después de 1 segundo con el valor "Éxito".',
              instruction: 'Usa "new Promise()" con resolve para cumplir la promesa.',
              type: 'code',
              initialCode: '// Crea una promesa que se resuelve con "Éxito"\nlet miPromesa = \n',
              expectedSolution: "let miPromesa = new Promise(function(resolve, reject) {\n  setTimeout(function() {\n    resolve('Éxito');\n  }, 1000);\n});",
              testCase: { shouldContain: 'new Promise', shouldContain: 'resolve' },
              points: 20,
              xp: 10,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Usar then y catch',
              description: 'Completa el código para manejar la resolución y rechazo de la promesa.',
              instruction: 'Usa .then() para el éxito y .catch() para el error.',
              type: 'code',
              initialCode: "let promesa = new Promise(function(resolve, reject) {\n  let exito = true;\n  if (exito) {\n    resolve('¡Todo bien!');\n  } else {\n    reject('Hubo un error');\n  }\n});\n\n// Agrega .then() y .catch() aquí\n",
              expectedSolution: "let promesa = new Promise(function(resolve, reject) {\n  let exito = true;\n  if (exito) {\n    resolve('¡Todo bien!');\n  } else {\n    reject('Hubo un error');\n  }\n});\n\npromesa\n  .then(function(resultado) { console.log(resultado); })\n  .catch(function(error) { console.log(error); });",
              testCase: { shouldContain: '.then', shouldContain: '.catch' },
              points: 20,
              xp: 10,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Promise.all()',
              description: '¿Qué hace Promise.all([promesa1, promesa2, promesa3])?',
              type: 'quiz',
              instruction: 'Selecciona la respuesta correcta.',
              quizOptions: [
                'Ejecuta las promesas en orden secuencial',
                'Se resuelve cuando TODAS las promesas se resuelven',
                'Se resuelve con la primera promesa que termine',
                'Rechaza si alguna promesa se resuelve',
              ],
              correctAnswer: 'Se resuelve cuando TODAS las promesas se resuelven',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
        {
          order: 3,
          name: 'Async/Await',
          description: 'Escribe código asíncrono de forma más legible con async/await.',
          difficulty: 'intermediate',
          concepts: ['async function', 'await', 'try/catch', 'error handling'],
          challenges: [
            {
              order: 1,
              title: 'Crear función async',
              description: 'Declara una función async llamada "obtenerDatos" que retorne una promesa resuelta.',
              instruction: 'Usa la palabra clave "async" antes de "function".',
              type: 'code',
              initialCode: '// Declara una función async\nasync function obtenerDatos() {\n  // Retorna un valor que automáticamente se convierte en promesa\n  return \n',
              expectedSolution: "async function obtenerDatos() {\n  return { nombre: 'Juan', edad: 30 };\n}",
              testCase: { shouldContain: 'async function', shouldContain: 'return' },
              points: 15,
              xp: 10,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Usar await',
              description: 'Usa await para esperar la resolución de la promesa dentro de la función async.',
              instruction: 'await solo se puede usar dentro de funciones async.',
              type: 'code',
              initialCode: "async function mostrarMensaje() {\n  let promesa = new Promise(function(resolve) {\n    setTimeout(function() {\n      resolve('¡Mensaje recibido!');\n    }, 1000);\n  });\n  \n  // Usa await aquí\n  let mensaje = \n  console.log(mensaje);\n}",
              expectedSolution: "async function mostrarMensaje() {\n  let promesa = new Promise(function(resolve) {\n    setTimeout(function() {\n      resolve('¡Mensaje recibido!');\n    }, 1000);\n  });\n  \n  let mensaje = await promesa;\n  console.log(mensaje);\n}",
              testCase: { shouldContain: 'await promesa' },
              points: 20,
              xp: 10,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Manejo de errores con try/catch',
              description: '¿Qué estructura se usa para manejar errores en funciones async con await?',
              type: 'quiz',
              instruction: 'Selecciona la respuesta correcta.',
              quizOptions: [
                'if/else',
                'try/catch',
                'switch/case',
                'do/while',
              ],
              correctAnswer: 'try/catch',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
      ],
    },
  ]

  // Create worlds with levels and challenges
  for (const worldData of worldsData) {
    console.log(`Creando mundo: ${worldData.name}`)
    
    const world = await prisma.world.create({
      data: {
        order: worldData.order,
        name: worldData.name,
        description: worldData.description,
        color: worldData.color,
        icon: worldData.icon,
        requiredLevel: worldData.requiredLevel,
        requiredXP: worldData.requiredXP,
        totalLevels: worldData.levels.length,
        totalChallenges: worldData.levels.reduce((acc, level) => acc + level.challenges.length, 0),
      },
    })

    for (const levelData of worldData.levels) {
      console.log(`  Creando nivel: ${levelData.name}`)
      
      const level = await prisma.level.create({
        data: {
          worldId: world.id,
          order: levelData.order,
          name: levelData.name,
          description: levelData.description,
          totalChallenges: levelData.challenges.length,
          pointsPerChallenge: levelData.challenges[0]?.points || 10,
          xpPerChallenge: levelData.challenges[0]?.xp || 5,
          concepts: levelData.concepts,
          difficulty: levelData.difficulty,
        },
      })

      for (const challengeData of levelData.challenges) {
        console.log(`    Creando desafío: ${challengeData.title}`)
        
        await prisma.challenge.create({
          data: {
            levelId: level.id,
            order: challengeData.order,
            title: challengeData.title,
            description: challengeData.description,
            instruction: challengeData.instruction,
            type: challengeData.type as any,
            initialCode: challengeData.initialCode,
            expectedSolution: challengeData.expectedSolution,
            testCase: challengeData.testCase,
            quizOptions: challengeData.quizOptions ? { options: challengeData.quizOptions } : undefined,
            correctAnswer: challengeData.correctAnswer,
            points: challengeData.points,
            xp: challengeData.xp,
            isRequired: challengeData.isRequired,
          },
        })
      }
    }

    // Unlock first world for the user
    await prisma.userWorldProgress.create({
      data: {
        userId: user.id,
        worldId: world.id,
        isUnlocked: world.order === 1, // Unlock first world
        unlockedAt: world.order === 1 ? new Date() : undefined,
      },
    })
  }

  console.log('Seed completado exitosamente!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
