import { PrismaClient } from '@prisma/client'
import * as bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('Iniciando seed de datos...')

  // Create test user
  const hashedPassword = await bcrypt.hash('password123', 10)
  
  const user = await prisma.user.upsert({
    where: { email: 'demo@jogaboneto.com' },
    update: {},
    create: {
      name: 'Usuario Demo',
      email: 'demo@jogaboneto.com',
      password: hashedPassword,
      userProgress: {
        create: {
          totalPoints: 0,
          currentLevel: 1,
          totalXP: 0,
          currentStreak: 1,
          maxStreak: 1,
          worldsCompleted: 0,
          challengesSolved: 0,
        },
      },
    },
  })

  console.log('Usuario creado:', user.email)

  // Create badges
  const badges = await prisma.badge.createMany({
    data: [
      {
        name: 'Primeros Pasos',
        description: 'Completa tu primer nivel de JavaScript',
        icon: '🎯',
        color: 'blue',
        type: 'challenges',
        criteria: { challengesSolved: 1 },
      },
      {
        name: 'Maestro de Variables',
        description: 'Completa el Mundo 1: Variables y Constantes',
        icon: '📦',
        color: 'purple',
        type: 'levels',
        criteria: { worldId: 1 },
      },
      {
        name: 'Ninja de Arrays',
        description: 'Completa el Mundo 6: Arrays',
        icon: '🥷',
        color: 'orange',
        type: 'levels',
        criteria: { worldId: 6 },
      },
      {
        name: 'Maestro Asincrono',
        description: 'Completa el Mundo 9: Asincronía',
        icon: '⚡',
        color: 'yellow',
        type: 'levels',
        criteria: { worldId: 9 },
      },
      {
        name: 'Racha de Fuego',
        description: '5 días consecutivos de práctica',
        icon: '🔥',
        color: 'red',
        type: 'streak',
        criteria: { streak: 5 },
      },
      {
        name: 'Explorador',
        description: 'Desbloquea 5 mundos diferentes',
        icon: '🗺️',
        color: 'green',
        type: 'worlds',
        criteria: { worldsUnlocked: 5 },
      },
      {
        name: 'Velocista',
        description: 'Completa un desafío en menos de 30 segundos',
        icon: '💨',
        color: 'cyan',
        type: 'speed',
        criteria: { timeUnderSeconds: 30 },
      },
      {
        name: 'Puntaje Perfecto',
        description: 'Obtén 1000 puntos totales',
        icon: '🏆',
        color: 'gold',
        type: 'points',
        criteria: { totalPoints: 1000 },
      },
    ],
  })

  console.log('Insignias creadas:', badges.length)

  // Create worlds and levels
  const worldsData = [
    {
      order: 1,
      name: 'Variables y Constantes',
      description: 'Aprende a declarar variables y constantes en JavaScript. Los fundamentos de la programación.',
      color: 'blue',
      icon: '🌱',
      requiredLevel: 1,
      requiredXP: 0,
      levels: [
        {
          order: 1,
          name: '¿Qué es una variable?',
          description: 'Aprende a declarar tu primera variable en JavaScript.',
          difficulty: 'beginner',
          concepts: ['let', 'const', 'var', 'declaración'],
          challenges: [
            {
              order: 1,
              title: 'Declara tu primera variable',
              description: 'Declara una variable llamada "nombre" y asígnale el valor "JogaBoneto".',
              instruction: 'Usa la palabra clave "let" para declarar la variable.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n\n',
              expectedSolution: 'let nombre = "JogaBoneto";',
              testCase: { shouldContain: 'let nombre = "JogaBoneto"' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Crear una constante',
              description: 'Crea una constante llamada "MAX_PUNTOS" con el valor 100.',
              instruction: 'Usa "const" para crear una constante que no puede cambiar.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n\n',
              expectedSolution: 'const MAX_PUNTOS = 100;',
              testCase: { shouldContain: 'const MAX_PUNTOS = 100' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Diferencia entre let y const',
              description: '¿Qué palabra clave usarías para un valor que va a cambiar?',
              type: 'quiz',
              instruction: 'Selecciona la respuesta correcta.',
              quizOptions: ['var', 'let', 'const', 'static'],
              correctAnswer: 'let',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
        {
          order: 2,
          name: 'Convenciones de nombres',
          description: 'Aprende buenas prácticas para nombrar tus variables.',
          difficulty: 'beginner',
          concepts: ['camelCase', 'snake_case', 'naming conventions'],
          challenges: [
            {
              order: 1,
              title: 'Nombre apropiado',
              description: 'Declara una variable para guardar el nombre de un usuario.',
              instruction: 'Usa camelCase para nombres compuestos.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n\n',
              expectedSolution: 'let nombreDeUsuario = "Juan";',
              testCase: { shouldContain: 'let nombreDeUsuario' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Constante mayúscula',
              description: 'Declara una constante para la gravedad terrestre.',
              instruction: 'Usa convención de nombres con MAYÚSCULAS para constantes.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n\n',
              expectedSolution: 'const GRAVEDAD_TERRESTRE = 9.8;',
              testCase: { shouldContain: 'const GRAVEDAD_TERRESTRE' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Buenas prácticas',
              description: '¿Cuál es la convención correcta en JavaScript moderno?',
              type: 'quiz',
              instruction: 'Selecciona la opción correcta.',
              quizOptions: [
                'SNAKE_CASE para todo',
                'camelCase para variables, UPPER_CASE para constantes',
                'kebab-case para variables',
                'PascalCase para variables',
              ],
              correctAnswer: 'camelCase para variables, UPPER_CASE para constantes',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
        {
          order: 3,
          name: 'Tipos de datos básicos',
          description: 'Aprende sobre strings, numbers y booleans.',
          difficulty: 'beginner',
          concepts: ['string', 'number', 'boolean', 'typeof'],
          challenges: [
            {
              order: 1,
              title: 'Crear un string',
              description: 'Declara una variable llamada "mensaje" que contenga el texto "Hola Mundo".',
              instruction: 'Usa comillas dobles o simples para crear strings.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n\n',
              expectedSolution: 'let mensaje = "Hola Mundo";',
              testCase: { shouldContain: 'let mensaje = "Hola Mundo"' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Crear un número',
              description: 'Declara una variable llamada "edad" que contenga el número 25.',
              instruction: 'Los números no llevan comillas.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n\n',
              expectedSolution: 'let edad = 25;',
              testCase: { shouldContain: 'let edad = 25' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Booleano verdadero',
              description: 'Crea una variable booleana llamada "esMayorDeEdad" que sea verdadera.',
              instruction: 'Usa las palabras clave true o false.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n\n',
              expectedSolution: 'let esMayorDeEdad = true;',
              testCase: { shouldContain: 'let esMayorDeEdad = true' },
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
      ],
    },
    {
      order: 2,
      name: 'Tipos de Datos Avanzados',
      description: 'Profundiza en null, undefined, Symbol y BigInt.',
      color: 'purple',
      icon: '🔮',
      requiredLevel: 2,
      requiredXP: 100,
      levels: [
        {
          order: 1,
          name: 'Null vs Undefined',
          description: 'Entiende la diferencia entre null y undefined.',
          difficulty: 'intermediate',
          concepts: ['null', 'undefined', 'tipos primitivos'],
          challenges: [
            {
              order: 1,
              title: 'Asignar null',
              description: 'Declara una variable "datos" que tenga el valor null.',
              instruction: 'null se usa cuando una variable intencionalmente no tiene valor.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n\n',
              expectedSolution: 'let datos = null;',
              testCase: { shouldContain: 'let datos = null' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Comprobar undefined',
              description: 'Crea una variable sin asignar valor.',
              instruction: 'Las variables declaradas sin asignar tienen valor undefined.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n\n',
              expectedSolution: 'let variableSinValor;',
              testCase: { shouldContain: 'let variableSinValor' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Tipo de null',
              description: '¿Qué devuelve typeof null?',
              type: 'quiz',
              instruction: 'Selecciona la respuesta correcta.',
              quizOptions: ['undefined', 'null', 'object', 'number'],
              correctAnswer: 'object',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
        {
          order: 2,
          name: 'BigInt y Symbol',
          description: 'Trabaja con números muy grandes y valores únicos.',
          difficulty: 'intermediate',
          concepts: ['BigInt', 'Symbol', 'tipos primitivos'],
          challenges: [
            {
              order: 1,
              title: 'Crear un BigInt',
              description: 'Declara un BigInt para el número 9007199254740991.',
              instruction: 'Usa BigInt() con n al final del número.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n\n',
              expectedSolution: 'let grande = 9007199254740991n;',
              testCase: { shouldContain: 'let grande = 9007199254740991n' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Crear un Symbol',
              description: 'Crea un Symbol con descripción "id-usuario".',
              instruction: 'Los Symbol son siempre únicos.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n\n',
              expectedSolution: 'let idUsuario = Symbol("id-usuario");',
              testCase: { shouldContain: 'let idUsuario = Symbol("id-usuario")' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Característica de Symbol',
              description: '¿Qué propiedad única tienen los Symbols?',
              type: 'quiz',
              instruction: 'Selecciona la respuesta correcta.',
              quizOptions: [
                'Son iterables',
                'Son siempre únicos',
                'Pueden ser convertidos a números',
                'Tienen valor predeterminado',
              ],
              correctAnswer: 'Son siempre únicos',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
        {
          order: 3,
          name: 'Conversión de tipos',
          description: 'Convierte entre diferentes tipos de datos.',
          difficulty: 'intermediate',
          concepts: ['String()', 'Number()', 'Boolean()', 'conversión'],
          challenges: [
            {
              order: 1,
              title: 'String a número',
              description: 'Convierte "42" a número.',
              instruction: 'Usa Number() o el operador +.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\nlet texto = "42";\n',
              expectedSolution: 'let numero = Number(text);',
              testCase: { shouldContain: 'let numero = Number(text)' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Número a string',
              description: 'Convierte 42 a string "42".',
              instruction: 'Usa String().',
              type: 'code',
              initialCode: '// Escribe tu código aquí\nlet numero = 42;\n',
              expectedSolution: 'let texto = String(numero);',
              testCase: { shouldContain: 'let texto = String(numero)' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Booleano a string',
              description: '¿Qué devuelve String(true)?',
              type: 'quiz',
              instruction: 'Selecciona la respuesta correcta.',
              quizOptions: ['true', '"true"', '1', 'undefined'],
              correctAnswer: '"true"',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
      ],
    },
    {
      order: 3,
      name: 'Operadores',
      description: 'Aritméticos, lógicos y de comparación.',
      color: 'green',
      icon: '➕',
      requiredLevel: 3,
      requiredXP: 200,
      levels: [
        {
          order: 1,
          name: 'Operadores Aritméticos',
          description: '+, -, *, /, % y más.',
          difficulty: 'beginner',
          concepts: ['+', '-', '*', '/', '%', 'operadores'],
          challenges: [
            {
              order: 1,
              title: 'Suma',
              description: 'Calcula 5 + 3 y guárdalo en una variable.',
              instruction: 'Usa el operador +.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n',
              expectedSolution: 'let resultado = 5 + 3;',
              testCase: { shouldContain: 'let resultado = 5 + 3' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Módulo',
              description: 'Calcula el módulo de 10 entre 3.',
              instruction: 'El operador % devuelve el residuo.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n',
              expectedSolution: 'let residuo = 10 % 3;',
              testCase: { shouldContain: 'let residuo = 10 % 3' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Exponenciación',
              description: 'Calcula 2 elevado a la 3 (2^3).',
              instruction: 'Usa el operador ** para potenciación.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n',
              expectedSolution: 'let potencia = 2 ** 3;',
              testCase: { shouldContain: 'let potencia = 2 ** 3' },
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
        {
          order: 2,
          name: 'Operadores de Comparación',
          description: '===, !==, <, >, <=, >=.',
          difficulty: 'beginner',
          concepts: ['===', '!==', '<', '>', '<=', '>='],
          challenges: [
            {
              order: 1,
              title: 'Igualdad estricta',
              description: 'Compara si 5 es igual a "5".',
              instruction: '=== compara valor y tipo.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n',
              expectedSolution: 'let esIgual = 5 === "5";',
              testCase: { shouldContain: 'let esIgual = 5 === "5"' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 2,
              title: 'Mayor que',
              description: 'Compara si 10 es mayor que 5.',
              instruction: 'Usa el operador >.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\n',
              expectedSolution: 'let esMayor = 10 > 5;',
              testCase: { shouldContain: 'let esMayor = 10 > 5' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 3,
              title: 'Diferente de',
              description: '¿Qué operador devuelve true si los valores son diferentes?',
              type: 'quiz',
              instruction: 'Selecciona la respuesta correcta.',
              quizOptions: ['==', '===', '!==', '='],
              correctAnswer: '!==',
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
        {
          order: 3,
          name: 'Operadores Lógicos',
          description: '&&, ||, ! y más.',
          difficulty: 'intermediate',
          concepts: ['&&', '||', '!', 'operadores lógicos'],
          challenges: [
            {
              order: 1,
              title: 'AND lógico',
              description: 'Verifica si esAdulto Y tieneLicencia.',
              instruction: 'Ambas condiciones deben ser verdaderas.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\nlet esAdulto = true;\nlet tieneLicencia = true;\n',
              expectedSolution: 'let puedeConducir = esAdulto && tieneLicencia;',
              testCase: { shouldContain: 'let puedeConducir = esAdulto && tieneLicencia' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 2,
              title: 'OR lógico',
              description: 'Verifica si esFinDeSemana O esVacación.',
              instruction: 'Al menos una condición debe ser verdadera.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\nlet esFinDeSemana = false;\nlet esVacación = true;\n',
              expectedSolution: 'let puedeDescansar = esFinDeSemana || esVacación;',
              testCase: { shouldContain: 'let puedeDescansar = esFinDeSemana || esVacación' },
              points: 10,
              xp: 5,
              isRequired: true,
            },
            {
              order: 3,
              title: 'NOT lógico',
              description: 'Invierte el valor de una boolean.',
              instruction: 'Usa el operador !.',
              type: 'code',
              initialCode: '// Escribe tu código aquí\nlet esVerdadero = true;\n',
              expectedSolution: 'let esFalso = !esVerdadero;',
              testCase: { shouldContain: 'let esFalso = !esVerdadero' },
              points: 10,
              xp: 5,
              isRequired: false,
            },
          ],
        },
      ],
    },
    // Worlds 4-9 would follow the same pattern...
    {
      order: 4,
      name: 'Control de Flujo',
      description: 'Condicionales if/else y bucles for/while.',
      color: 'orange',
      icon: '🔀',
      requiredLevel: 4,
      requiredXP: 300,
      levels: [],
    },
    {
      order: 5,
      name: 'Funciones',
      description: 'Declaración, expresión, flecha y más.',
      color: 'red',
      icon: '📦',
      requiredLevel: 5,
      requiredXP: 400,
      levels: [],
    },
    {
      order: 6,
      name: 'Arrays',
      description: 'Creación, métodos y manipulación de arrays.',
      color: 'pink',
      icon: '🥷',
      requiredLevel: 6,
      requiredXP: 500,
      levels: [],
    },
    {
      order: 7,
      name: 'Objetos',
      description: 'Propiedades, métodos y clases básicas.',
      color: 'indigo',
      icon: '💎',
      requiredLevel: 7,
      requiredXP: 600,
      levels: [],
    },
    {
      order: 8,
      name: 'DOM Manipulation',
      description: 'Seleccionar, modificar y crear elementos HTML.',
      color: 'teal',
      icon: '🌐',
      requiredLevel: 8,
      requiredXP: 700,
      levels: [],
    },
    {
      order: 9,
      name: 'Asincronía',
      description: 'Promesas, async/await y fetch API.',
      color: 'yellow',
      icon: '⚡',
      requiredLevel: 9,
      requiredXP: 800,
      levels: [],
    },
  ]

  // Create worlds with levels and challenges
  for (const worldData of worldsData) {
    console.log(`Creando mundo: ${worldData.name}`)
    
    const world = await prisma.world.create({
      data: {
        order: worldData.order,
        name: worldData.name,
        description: worldData.description,
        color: worldData.color,
        icon: worldData.icon,
        requiredLevel: worldData.requiredLevel,
        requiredXP: worldData.requiredXP,
        totalLevels: worldData.levels.length,
        totalChallenges: worldData.levels.reduce((acc, level) => acc + level.challenges.length, 0),
      },
    })

    for (const levelData of worldData.levels) {
      console.log(`  Creando nivel: ${levelData.name}`)
      
      const level = await prisma.level.create({
        data: {
          worldId: world.id,
          order: levelData.order,
          name: levelData.name,
          description: levelData.description,
          totalChallenges: levelData.challenges.length,
          pointsPerChallenge: levelData.challenges[0]?.points || 10,
          xpPerChallenge: levelData.challenges[0]?.xp || 5,
          concepts: levelData.concepts,
          difficulty: levelData.difficulty,
        },
      })

      for (const challengeData of levelData.challenges) {
        console.log(`    Creando desafío: ${challengeData.title}`)
        
        await prisma.challenge.create({
          data: {
            levelId: level.id,
            order: challengeData.order,
            title: challengeData.title,
            description: challengeData.description,
            instruction: challengeData.instruction,
            type: challengeData.type as any,
            initialCode: challengeData.initialCode,
            expectedSolution: challengeData.expectedSolution,
            testCase: challengeData.testCase,
            quizOptions: challengeData.quizOptions ? { options: challengeData.quizOptions } : undefined,
            correctAnswer: challengeData.correctAnswer,
            points: challengeData.points,
            xp: challengeData.xp,
            isRequired: challengeData.isRequired,
          },
        })
      }
    }

    // Unlock first world for the user
    await prisma.userWorldProgress.create({
      data: {
        userId: user.id,
        worldId: world.id,
        isUnlocked: world.order === 1, // Unlock first world
        unlockedAt: world.order === 1 ? new Date() : undefined,
      },
    })
  }

  console.log('Seed completado exitosamente!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
